name: ruff

on:
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/ruff.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '.github/workflows/ruff.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1.0.0
        with:
          args: check . --output-format=github
